### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Brunner246**

### CODE REVIEW

**Review by jspaquet — CHANGES_REQUESTED** [review]
A lot of files are encoded with UTF-16 with BOM. Can you ensure every **text** file is in UTF-8 without BOM?

**Review by jspaquet — CHANGES_REQUESTED** [review]
I think docs/requirements.txt is still in UTF16. It's showing up as a binary in diff view. This is the file used to build the docs on RTD.

**Comment by Brunner246** [comment]
Requirements.txt is now pure UTF-8  @jspaquet 

The file is built from pip-compile requirements.in

**Comment by Brunner246** [comment]
Reopend request after accidently closing it

**Review by jspaquet — APPROVED** [review]

**Pull request merged**
